[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = '''
      default-src 'self' https:;
      connect-src 'self';
      object-src 'none';
      img-src 'self' https: data:;
      style-src  'self' 'unsafe-inline';
      script-src 'self' 'unsafe-inline';
      script-src-elem 'self' https://storage.googleapis.com https://www.google-analytics.com/analytics.js 'sha256-xrvJjXPsVTsDWETQpggIjt8GbIuC6Sc86vw0ry9JYG4=';'''

[[redirects]]
  from = "/about*"
  to = "/me:splat"
  status = 301